import HomeIcon from './HomeIcon.jsx'
import FoodIcon from './FoodIcon.jsx'
import DrinkIcon from './DrinkIcon.jsx'
import HistoryIcon from './HistoryIcon.jsx'
import WalletIcon from './WalletIcon.jsx'
import PromoIcon from './PromoIcon.jsx'
import SettingIcon from './SettingIcon.jsx'
import OpenIcon from './OpenIcon.jsx'
import CloseIcon from './CloseIcon.jsx'
import AddPersonIcon from './AddPersonIcon.jsx'
import ProductIcon from './ProductIcon.jsx'
import OrderIcon from './OrderIcon.jsx'
import SalesIcon from './SalesIcon.jsx'

export { HomeIcon, FoodIcon, DrinkIcon, HistoryIcon, WalletIcon, PromoIcon, SettingIcon, OpenIcon, CloseIcon, OrderIcon, SalesIcon, ProductIcon, AddPersonIcon }
